### ISSUE TITLE
Move CorsOptions to root namespace

### ISSUE THREAD

**Issue by pranavkm** [aspnet/CORS#120]
It's in the infrastructure namespace `Microsoft.AspNetCore.Cors.Infrastructure` which feels a bit odd for something we expect users to use.

**Comment by Eilon** [comment]
It's a breaking change and the value is too low. Sorry 😢 Also, due to the primary usage being via an `Action<CorsOptions>`, users in general won't see the type name - only our own codebase uses it by name.
