### ISSUE TITLE
Add an empty constructor for EnableCorsAttribute 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/CORS#122]
To use the default CORS policy, we need to pass in either `null` or `CorsOptions.DefaultPolicyName`. The latter is an instance member and therefore cannot be used in an attribute. It would be nice to substitute  `[EnableCors(null)]` with `[EnableCors]`. Additionally, it would be nice if we had an (extension?) method on `CorsOptions` that allowed setting the default policy e.g. `options.AddDefaultCorsPolicy(builder => ..` instead of doing `options.AddPolicy(options.DefaultPolicyName, builder => `

**Comment by Eilon** [comment]
These all sound like good ideas.

The `AddDefaultCorsPolicy` method should be `AddDefaultPolicy` because CORS is already implied.

**Comment by kichalla** [comment]
Apart from adding a default constructor to `EnableCorsAttribute` (which helps MVC scenarios), we probably need to do the same for `UseCors` extension too as it currently expects to provide a policy name always.
https://github.com/aspnet/CORS/blob/dev/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsMiddlewareExtensions.cs#L20

**Comment by Eilon** [comment]
That seems perfectly reasonable.

**Comment by kichalla** [comment]
5eae687ddd2f1a297b39a4099fa52e9280517a33
