### ISSUE TITLE
Using a stricter CORS policy for just one controller

### ISSUE THREAD

**Issue by nstohler** [aspnet/CORS#127]
For ASP.NET Core 2.0

How can apply a stricter CORS policy for just one controller with a "global" (more open) CORS policy already in place? 

I added a CORS policy that is very open, so my Angular client has the access it needs. 

Now I need to have a stricter CORS policy for just one controller (or methods). I've tried adding the `[DisableCors] `attribute to the controller. I added the `[EnableCors("StricterPolicy")]` to some actions, but it's still letting the requests through (I'm trying this locally so far). 

Only if I comment out the call in `Startup Configure() ` to `app.UserCors("GlobalPolicy")`, the stricter policy works. But then I would need to decorate all my other controllers to get the GlobalPolicy working again.

**Comment by Eilon** [comment]
@kichalla / @jbagga - do you know if this is possible to do with the system we have today?

Also cc @blowdart in case you happen to know.

**Comment by jbagga** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/cors#enabling-cors-in-mvc
`UseCors` is using the CORS middleware which is different from MVC. Can you try the following?

1. Add a filter for the global policy
```
    services.Configure<MvcOptions>(options =>
    {
        options.Filters.Add(new CorsAuthorizationFilterFactory("GlobalPolicy"));
    });
```
2. Decorate the actions that require a stricter policy with `[EnableCors("StricterPolicy")]`

> Action-level policies take precedence over controller-level policies, and controller-level policies take precedence over global policies.

This should work. But if not, please let us know and share the Startup configurations. I will investigate this further then.

cc @kichalla

**Comment by nstohler** [comment]
That worked! Thanks. 

I'm still a bit confused about the CORS middleware/MVC distinction (maybe I should read more about this). 

I ended up adding my own middleware still, cause I had to make sure some actions could only be called from another (known) server.
