### ISSUE TITLE
Remove duplicate header names and method constants

### ISSUE THREAD

**Issue by Tratcher** [aspnet/CORS#130]
https://github.com/aspnet/CORS/blob/df571655acafb39703935a71a977feec023977d0/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsConstants.cs contains header and method string constants that are duplicated with constants in HttpAbstractions.

See
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/HeaderNames.cs
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HttpMethods.cs

The public constants can redirect for now. E.g. `public static readonly string AccessControlMaxAge = HeaderNames.AccessControlMaxAge;`

The internal lists can also be updated to use the HttpAbstractions constants.
https://github.com/aspnet/CORS/blob/df571655acafb39703935a71a977feec023977d0/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsConstants.cs#L66-L89

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2319
