### ISSUE TITLE
Should CORS be abandoned?

### ISSUE THREAD

**Issue by jackzhp** [aspnet/CORS#131]
I think that CORS design is completely unnecessary, and so should be abandoned. I have laid down my arguments, if you think you know this issue pretty well, would you please look at it, and comment it.

https://github.com/jackzhp/CORS-should-retire

**Comment by Eilon** [comment]
Hi @jackzhp , the CORS component is an optional component that developers can choose to use when appropriate. There are of course many different solutions for making cross-origin requests, and CORS continues to be a very popular, widely adopted pattern.
