### ISSUE TITLE
EnableCors security and client application concerns

### ISSUE THREAD

**Issue by ole1986** [aspnet/CORS#136]
I am little concerned about the EnableCors used in ASp.NEt Core.

As we know by doing the below:
```
services.AddCors(o => {
    o.AddPolicy("Api", builder => builder.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader().AllowCredentials());
});
```
I can use the `EnableCors("Api")` to allow XmlHTTPRequest from a different domain.

But what if I use client applications like "Postman" to call my ApiController.
As far as I know Postman does not include the origin and acts as a regular browser.
So `EnableCors([..])` is useless in this case.

Shouldn't `EnableCors([...])` disallow such requests and only allow "real" cross-domain requests by checking for header `Origin`? But what if I now fake the `Origin` header?

Also am I the only one missing some Cors related authorization attributes, like
`CorsAuthorizeAttribute()` and **an option / method** to get the policy being applied?

Thank you in advanced

---
Version Info
ASP.NET Core: 2.0.0
Version Studio 2017 15.5.1

**Comment by rynowak** [comment]
CORS requires the cooperation of the client, and only adds value when your end user is a browser. 

Enforcing the presence or validity of the `Origin` header doesn't add any security by itself, because any malicious client could send an `Origin` header with a value you expect, there's nothing secret about it.

CORS only works in practice because the browser you end user is using looks at the CORS response headers.

**Comment by ole1986** [comment]
"Enforcing the presence or validity of the Origin header doesn't add any security by itself, because any malicious client could send an Origin header with a value you expect, there's nothing secret about it.", -, that ist what i was actually asking

So question is here how to become such things more secure... 

API Keys can easily be copied... So what else, antiforgerytoken, OK what else.

I still think it's insecure... So I was asking about ideas not repeating my questions to be honest.

**Comment by rynowak** [comment]
> So question is here how to become such things more secure...

**Comment by rynowak** [comment]
Sorry, I think misunderstood what you're asking 😕 

----------

Let's step back a minute, what is your app and who are your clients/end users? Are you securing an API that other apps are going to call? Is this a website that users visit using a browser? both?

CORS and antiforgery and mitigations for some specific issues you have to deal with when your clients are browsers. 

----

tagging @blowdart @Tratcher  as well in case they want to help provide guidance.

**Comment by brockallen** [comment]
> So question is here how to become such things more secure...
> API Keys can easily be copied... So what else, antiforgerytoken, OK what else.
> I still think it's insecure... So I was asking about ideas not repeating my questions to be honest.

HTTP token binding would be the next level of protection.

**Comment by blowdart** [comment]
CORS is meant for user-agents that support it, which generally is well-behaved browsers. PostMan is not a browser and does not implement CORS, so it's allowed to just go where it wants. CORS does not require you to stop any non-compliant CORS requests because the backend cannot validate what is, and isn't valid, it's a client side check. It's like an old HTTP Refer check, malicious code can spoof this, so if you want to protect something you authenticate it.

As @brockallen says this would be the token binding would be some help against copying, but only for things that the server issues, like authentication tokens, or anti-forgery tokens.

**Comment by ole1986** [comment]
@rynowak thank you for reopening.

My goal is to implement something like this as a Web Api:
1. Only a single request should securely authenticate and fetch the necessary information (if authorized of course)
2. ApiController should either be used openly (no-auth, no api key) for specific Controller->Action
3. ApiController should allow calls from SAME  domain using authenticated user (AuthorizeAttribute)
4. ApiController should support cross domain access ONLY using either APIKEY
5. ApiController should allow mixed mode (user credentials / APIKEY) for specific Controller->Action

For this I already implemented an Authorization/Action-Filter which I am actually not sure if this is the proper way to do. Because of point 1. (single request) I havent implemented HTTP token binding as I think there is no other way to do it with an additonal request (before).

Are there any other ideas or native methods which may help me instead of writing my own authorization filter(s)

Many thanks in advanced for any hints and recommendations!

**Comment by brockallen** [comment]
IMO, having a single API support several different authentication mechanisms is adding complexity, which hurts security. The modern design for this is to centralize security behind a token server, and then the API only trusts tokens from the one token server. Let the token server support the various authentication mechanisms you want to support. That way it's in one place and the API is abstracted form it all. The OAuth2 protocol is then how the client app obtains token to invoke the API.

**Comment by mkArtakMSFT** [comment]
Hi @ole1986, seems like what you're describing is a custom security configuration which you will be able to achieve with authentication model described by @brockallen.

**Comment by ole1986** [comment]
@brockallen I agree CORS is not auth. but most often CORS and auth will come together and what I see is a possible lack of "explanation" on how to properly implement both things together (easily).

**To phrase this into a final question which I think I am actually concerned about**
How can I quickly implement an authentication concept (like OAuth) using CORS?

And these are possible answers:
https://identityserver4.readthedocs.io/en/dev/quickstarts/6_aspnet_identity.html (+next page)
https://github.com/IdentityServer/IdentityServer4
https://identityserver4.readthedocs.io/en/dev/quickstarts/6_aspnet_identity.html

Thank you!
