### ISSUE TITLE
What is the purpose of separating AddCors and ConfigureCors?

### ISSUE THREAD

**Issue by davidpeden3** [aspnet/CORS#14]
Why doesn't `AddCors` just take an optional `CorsOptions`?

**Comment by Eilon** [comment]
I think this is the general pattern that's used throughout all the new components. The idea is that you'd only ever call `AddXyz` once (you need the services it adds only once - adding them more than once does nothing), but you can call `ConfigureXyz` multiple times to have different bits of your app participate in the configuration of that component.
