### ISSUE TITLE
Chrome treats any non-200 responses to preflight requests as a failure

### ISSUE THREAD

**Issue by danroth27** [aspnet/CORS#19]
From @sandorfr (originally filed as aspnet/mvc#2542)

Looks like the current implementation of cors return a 204 for preflight request and it looks like Chrome considers any non-200 being a failure. Doing some quick research on the web I've seen that there is discussions about what should be the good behavior but what I'm sure of is that we need that to just work. Maybe we should be able to configure it?

**Comment by sandorfr** [comment]
There is a sample request
**Request headers**
```
OPTIONS /api/User/login/foursquare HTTP/1.1
Host: foodspot-api-2-staging.azurewebsites.net
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://petstore.swagger.io
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
Access-Control-Request-Headers: accept, content-type
Accept: */*
Referer: http://petstore.swagger.io/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fr-FR;q=0.6,fr;q=0.4
```
**Answer Headers**
```
HTTP/1.1 204 No Content
Server: Microsoft-IIS/8.0
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=354ba239928626ceb46c25fd489ba28a8a0abb810adeb89ccbdc7087fc8cb50b;Path=/;Domain=asamplesite.azurewebsites.net
Date: Tue, 12 May 2015 18:17:10 GMT
X-Cache: MISS from m00180A11A128
X-Cache-Lookup: MISS from m00180A11A128:3128
Via: 1.1 m00180A11A128 (squid/3.3.5)
Connection: close
```

After further search I'm wondering if it is really the 204 which causes the failure. Infomartion I've found about this is actually old ( such as https://bugzilla.mozilla.org/show_bug.cgi?id=845881). But I noticed One big difference between your implementation and mine. I'm setting this headers `Access-Control-Allow-Origin`, `Access-Control-Allow-Headers`, `Access-Control-Allow-Methods`, `Access-Control-Expose-Headers` and it appears that your middleware does not.

**Comment by guigobavaresco** [comment]
Similar issue of @sandorfr. Using beta 4, setting headers, receiving 204 for preflight request, run and tested with Chrome, future POST does not occurs and ```No 'Access-Control-Allow-Origin' header is present on the requested resource.``` appears on console.

Source
```
services.AddCors();
services.ConfigureCors(options =>
    options.AddPolicy(this._corsPolicy, builder =>
         builder.WithOrigins(new string[] { "http://localhost:3429" })
                    .WithHeaders(new string[] { "Content-Type, x-xsrf-token" })
                    .WithMethods(new string[] { "DELETE, PUT, GET, POST" })
                    .AllowCredentials()
                    .Build()));

app.UseCors(this._corsPolicy);
```

Before this, I was using the source below: 

``` 
app.Use(async (context, next) =>
{
    context.Response.Headers.Add("Access-Control-Allow-Origin", new[] { "http://localhost:3429" });
    context.Response.Headers.Add("Access-Control-Allow-Headers", new[] { "Content-Type, x-xsrf-token" });
    context.Response.Headers.Add("Access-Control-Allow-Methods", new[] { "DELETE, PUT, GET, POST" });                            
    await next();
});
``` 
and a strange situation appears: preflight request was hitting Controller Action, so, for example, below test on Method returns ```true```.
``` 
   if (this.Context.Request.Method == "OPTIONS")
```
It seems a bug or some conf. I made wrong. And If I decorate my class with data annotation ```Authorize``` (using simple cookie middleware auth) then I get a 401 for preflight. Is it correct?

Now I think I should use middleware Cors. So if possible, I would like to have some code working or a possible date to.

Thanks

**Comment by sandorfr** [comment]
@danroth27 Just letting you know I'm willing to work on a fix for that issue if you want so.

**Comment by harshgMSFT** [comment]
@sandorfr not sure what you are observing, from your response headers, it seems that you are missing required headers (which might be because your policy didnt match) and hence are seeing an error. 
Here is a preflight request that I sent and the sample response:

Pre flight Request
```
OPTIONS http://domain2.com/cors2/Home/Index HTTP/1.1
Host: domain2.com
Connection: keep-alive
Access-Control-Request-Method: GET
Origin: http://domain1.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Access-Control-Request-Headers: adadadad
Accept: */*
Referer: http://domain1.com/cors
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

Pre-Flight Response
```
HTTP/1.1 204 No Content
Server: Microsoft-IIS/10.0
Access-Control-Allow-Origin: http://domain1.com
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: adadadad
X-Powered-By: ASP.NET
Date: Fri, 29 May 2015 21:52:47 GMT
```

Actual request : 
```
GET http://domain2.com/cors2/Home/Index HTTP/1.1
Host: domain2.com
Connection: keep-alive
Origin: http://domain1.com
adadadad: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Accept: */*
Referer: http://domain1.com/cors
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

Actual response
```
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Server: Microsoft-IIS/10.0
Access-Control-Allow-Origin: http://domain1.com
Access-Control-Allow-Credentials: true
X-Powered-By: ASP.NET
Date: Fri, 29 May 2015 21:52:47 GMT
Content-Length: 4

App2
```

It will be helpful if you share your configuration in startup.cs (assuming you are using a middleware).

**Comment by harshgMSFT** [comment]
@rsbavaresco 

There is a problem in the way you are configuring your application. You are configuring cors within mvc as well as adding a cors middleware, was that intentional? I am inclined to think otherwise. 

##### Here is how you configure just the middleware 
https://github.com/aspnet/Mvc/blob/dev/test/WebSites/CorsMiddlewareWebSite/Startup.cs

##### Here is how you configure just mvc for cors support. 

https://github.com/aspnet/Mvc/blob/dev/test/WebSites/CorsWebSite/Startup.cs

and then use it like so
https://github.com/aspnet/Mvc/blob/dev/test/WebSites/CorsWebSite/Controllers/BlogController.cs#L19


I think the problem with your application is you are using complete strings instead of a comma separated string array. 
Do 
```c#
services.ConfigureCors(options =>
                 options.AddPolicy("someName", builder =>
						  builder.WithOrigins("http://domain1.com" )                                  
								 .WithHeaders(new string[] { "Content-Type", "x-xsrf-token", "customHeader" })
                                 .WithMethods(new string[] { "GET", "POST" })));
```
instead of 
```c#
.WithHeaders(new string[] { "Content-Type, x-xsrf-token" })
.WithMethods(new string[] { "DELETE, PUT, GET, POST" })
```

**Comment by rsbavaresco** [comment]
@harshgMSFT thanks for your time.

Now I have a CorsMiddleware and a simple policy applied for entire application, only what is shown below, nothing more confs.
```
    app.UseCors(builder => 
                builder.WithOrigins("http://localhost:3429")
                       .WithHeaders(new string[] { "Content-Type", "authorization", "x-xsrf-token" })
                       .WithMethods(new string[] { "DELETE", "PUT", "GET", "POST" })
                       .AllowCredentials());
```
At Chrome, the result of above confs is the same as my previous post, and comma separated string array does not have effect.
 
1) GET method does not makes Preflight and works, Response with 200 OK.
2) POST method makes Preflight. Headers detail: 

Preflight Request Header
```
OPTIONS /api/... HTTP/1.1
Host: localhost:5801
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:3429
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Access-Control-Request-Headers: accept, content-type
Accept: */*
Referer: http://localhost:3429/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,pt;q=0.6
```
Preflight Response Header
```
HTTP/1.1 204 No Content
Server: Microsoft-IIS/10.0
X-SourceFiles: =?UTF ...
X-Powered-By: ASP.NET
Date: Mon, 01 Jun 2015 14:10:24 GMT
```
And nothing more occurs.

Ps: If I use only services to Configure Cors and Add Policy then EnableCors("policy") in Controller, Preflight of POST returns 401.

**Comment by brockallen** [comment]
FWIW, the spec says that 204 is a valid preflight response code: http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0

**Comment by harshgMSFT** [comment]
@rsbavaresco 
Your preflight response tells me that your policy did not match. That is why you have a 204 and no AccessControl headers .. (and that is why your second call does not go through). 
I am curious though,GET, POST are a simple request unless you are sending custom headers, or content type http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0 
so if you are just chaging the verb from GET to POST, it should not change anything. 
(Also are you trying on your local machine ? if you are then i am not sure how it is working for you. As for localhost making a call to localhost, it is the same origin, so access control headers should not interfere.) 
If you are using IIS, to host please make sure the OPTIONS handler is turned off (i.e adding a section like so in your web.config
```
<modules runAllManagedModulesForAllRequests="false">
      <remove name="FormsAuthenticationModule" />
    </modules>
    <handlers>
      <remove name="OPTIONSVerbHandler" />
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
  </system.webServer>
```


for the scenario where you are trying with EnableCors policy, i suspect you have Authorization configured somewhere in your app. That is why you see 401, CORS does not ever return a 401. 

HTH

**Comment by sandorfr** [comment]
Hi,

I was able to point to the root cause of my policy to be rejected. Apparently, if we want to use `WithHeaders` instead of `AllowAnyHeaders` we also have to specify some standard headers such as "accept".

Not working :
```csharp
 app.UseCors(builder => builder
                .AllowAnyOrigin()
                .WithHeaders("X-Requested-With", "authenticationToken", "applicationToken", "content-type", "time-zone-offset", "api-version")
                .WithMethods("GET", "PATCH", "PUT", "DELETE", "POST")
                .WithExposedHeaders("new-authentication-token"));
```

Working :
```csharp
         app.UseCors(builder => builder
                .AllowAnyOrigin()
                .WithHeaders("accept", "accept-encoding", "accept-language", "X-Requested-With", "authenticationToken", "applicationToken", "content-type", "time-zone-offset", "api-version")
                .WithMethods("GET", "PATCH", "PUT", "DELETE", "POST")
                .WithExposedHeaders("new-authentication-token"));
```

So basically there is no issue (just something worth noting in the upcoming documentation).

BTW, the Options Handler will trap a lot of people especially with windows azure website hosting :)

**Comment by rsbavaresco** [comment]
@sandorfr that's it!

**Comment by harshgMSFT** [comment]
@danroth27 lets ensure that this gets documented.
