### ISSUE TITLE
CORS policy.WithOrigins("...") does not work?

### ISSUE THREAD

**Issue by MiguelLattuada** [aspnet/CORS#20]
Apparently the method AllowAnyOrigin() works fine adding the "Access-Control-Allow-Origin: * " header to the response.

![allowanyorigin](https://cloud.githubusercontent.com/assets/5618566/7671243/a2018278-fc9c-11e4-8648-f838972470bf.png)

But what's going on with WithOrigins("..."), It does not add the "Access-Control-Allow-Origin: ... " header to the response.

![withorigins](https://cloud.githubusercontent.com/assets/5618566/7671247/d3b1afe6-fc9c-11e4-95ba-858f362cd933.png)

Shouldn't it add something like...
```
  "Access-Control-Allow-Origin: http://addeddorigin.com/ "
```
?

**My code:**
```
services.ConfigureCors( config => config.AddPolicy("AddSingle",
                policy => policy
                    .WithOrigins("http://localhost:9000/")
                    .AllowAnyMethod() 
            ));
```

**Comment by harshgMSFT** [comment]
Did you configure your policy on the action that you are calling? 
This should not be happening and you should see `  "Access-Control-Allow-Origin: http://localhost:9000/ " Can you share your repro application?

**Comment by henkmollema** [comment]
This actually does work, but obviously only if you configure the policy. For example:
```csharp
app.UseCors("AddSingle");
```
