### ISSUE TITLE
Update CORS package version

### ISSUE THREAD

**Issue by danroth27** [aspnet/CORS#24]
Microsoft.AspNet.Cors is an existing package that we shipped for Katana. We should either update the version of the new functionality to 6.0.0 or use a different package ID.

**Comment by danroth27** [comment]
We decided to up the version to 6.0.0.

**Comment by Eilon** [comment]
This one is Announcements worthy. People have to update their projects.

**Comment by Eilon** [comment]
Why re-open this?

**Comment by pranavkm** [comment]
I linked to this work item as a discussion thread.

**Comment by Eilon** [comment]
Yeah but this issue is fixed... it needs to be closed.
