### ISSUE TITLE
Missing CorsMiddleware

### ISSUE THREAD

**Issue by logitron** [aspnet/CORS#25]
After upgrading a project to beta6 and installing the Microsoft.AspNet.Cors.Core 1.0.0-beta6 package, there is no longer the 'UseCors' extension for using the 'CorsMiddleware' component.  'ConfigureCors' and 'AddCors' still exist, but not 'UseCors'.  I assumed this was removed, but after downloading the CORS beta6 release from GitHub, those components seem to still exist.

**Comment by danroth27** [comment]
The `UseCors` extension method is actually currently in the `Microsoft.AspNet.Cors` package.
