### ISSUE TITLE
Preflight requests

### ISSUE THREAD

**Issue by franguyen** [aspnet/CORS#26]
Preflight requests don't seem to work (tried with beta5 and beta6).
I have a project that uses CORS and MVC with the following Startup.cs

        public void ConfigureServices(IServiceCollection services)
        {
            services.ConfigureCors(options =>
            {
                options.AddPolicy("AllowAll",
                    builder =>
                    {
                        builder.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader();
                    });
            });
            services.AddCors();
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseStaticFiles();
            app.UseMvc();
        }

I decorated my controller with ```[EnableCors("AllowAll")]```

I can perform simple requests with no issues however when a preflight request is involved the response lacks ```Access-Control-Allow-Origin```, ```Access-Control-Allow-Method``` and ```Access-Control-Allow-Headers```

This is the preflight request:
```
OPTIONS http://localhost:17477/api/Restaurant HTTP/1.1
Host: localhost:17477
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Origin: http://run.plnkr.co
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

And the response:
```
HTTP/1.1 200 OK
Allow: OPTIONS, TRACE, GET, HEAD, POST
Server: Microsoft-IIS/10.0
Public: OPTIONS, TRACE, GET, HEAD, POST
X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNcZnJhbmNvaXMubmd1eWVuXFNvdXJjZVxSZXBvc1xQcm9qZWN0QnJhaVxzcmNcRGVsaWV2cnlBUElcd3d3cm9vdFxhcGlcUmVzdGF1cmFudA==?=
X-Powered-By: ASP.NET
Date: Fri, 31 Jul 2015 12:01:14 GMT
Content-Length: 0
```

The preflight request happens because the Content-Type is ```application/json```

**Comment by danroth27** [comment]
I'm guessing something in IIS is handling the OPTIONS request before it even makes it to the CORS middleware. To verify try running the app on `WebListener` and see if the problem goes away.

Try adding the following to your web.config when running on IIS:

``` xml
  <system.webServer>
    <handlers>
      <remove name="OPTIONSVerbHandler"/>
      <remove name="TRACEVerbHandler"/>
    </handlers>
  </system.webServer>
```

**Comment by franguyen** [comment]
You got it right.

The ```web.config``` file was missing due to the project being created from the Empty template on VS.
I added a ```web.config``` with your settings and it fixed the issue.

I also got no issues running with ```WebListener```

Thanks for your help!
