### ISSUE TITLE
CORS middleware doesn't work if placed after MVC

### ISSUE THREAD

**Issue by Elinos** [aspnet/CORS#31]
If you load CORS after MVC middleware, it's not working.
Here is my Startup.cs code:

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.ConfigureCors(options => options.AddPolicy("allowAll", p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseStaticFiles();
            app.UseMvc();
            app.UseCors("allowAll");
        }

if I load it like this:

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseStaticFiles();
            app.UseCors("allowAll");
            app.UseMvc();
        }

it works!

**Comment by davidfowl** [comment]
Yes that's because middlewaee order matters. The cors middleware probably isn't running at all because mvc is handling the request.

**Comment by davidfowl** [comment]
See http://docs.asp.net/en/latest/fundamentals/middleware.html to learn more about middleware

**Comment by Avalaxy** [comment]
I ran into this issue as well. It isn't documented here: http://docs.asp.net/en/latest/security/cors.html.
