### ISSUE TITLE
CORS header comparisons should be case-insensitive

### ISSUE THREAD

**Issue by Eilon** [aspnet/CORS#32]
Per the spec:

http://www.w3.org/TR/cors/#terminology

> A header is said to be a simple header if the header field name is an ASCII case-insensitive match for Accept, Accept-Language, or Content-Language or if it is an ASCII case-insensitive match for Content-Type and the header field value media type (excluding parameters) is an ASCII case-insensitive match for application/x-www-form-urlencoded, multipart/form-data, or text/plain.

**Comment by kichalla** [comment]
38728a6bcd11bfe2c5f9c1b17fde1892bf499553

**Comment by Eilon** [comment]
@kichalla please update the labels on this issue!

**Comment by kichalla** [comment]
Sure, I added `Done` label. Thanks.

**Comment by Eilon** [comment]
And remove the other status labels please thanks :smile:
