### ISSUE TITLE
[Announcement] Microsoft.AspNet.Cors version changed to 6.0.0

### ISSUE THREAD

**Issue by pranavkm** [aspnet/CORS#38]
Discussion thread for https://github.com/aspnet/Announcements/issues/73

**Comment by henkmollema** [comment]
@pranavkm aspnet/Announcements#73 still links to #24, which is closed.

**Comment by pranavkm** [comment]
@henkmollema sorry about that. Fixed.

**Comment by henkmollema** [comment]
Great! :smile:

**Comment by snapbatch** [comment]
@pranavkm @Eilon  I am having issues adding two dependencies to support 
"Microsoft.AspNet.Cors": "6.0.0-beta8-15719",
and

"Microsoft.AspNet.Cors": "5.2.3",
 "dependencies": {
                "Microsoft.AspNet.Cors": "6.0.0-beta8-15719",
                "Microsoft.AspNet.Cors": "5.2.3",
}

If I remove 1 the other fails. Is there a way to support both?

**Comment by pranavkm** [comment]
Dnx does not allow a project to reference two versions of the same package.

**Comment by snapbatch** [comment]
@pranavkm they cant be the same package because when I remove 5.2.3 I lose support for System.Web.Cors, but when I remove beta-8 I looks support for IApplicationBuilder.UseCors

**Comment by snapbatch** [comment]
Ive created our own CorsPolicy which is implementing ICorsPolicyProvider which required Microsoft.AspNet.Cors": "5.2.3

**Comment by pranavkm** [comment]
Running ASP.NET 4.6 components inside of DNX isn't supported. You'd need to port your class library to target the policy provider in Microsoft.AspNet.Cors.Core - https://github.com/aspnet/CORS/blob/dev/src/Microsoft.AspNet.Cors.Core/ICorsPolicyProvider.cs

**Comment by snapbatch** [comment]
Thanks @pranavkm does the dnx support ICorsPolicyProviderFactory? I am trying to set my cors using the method HttpConfiguration.SetCorsPolicyProviderFactory

**Comment by pranavkm** [comment]
Add your custom provider to the DI container in Startup - 
```C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddTransient<ICorsPolicyProvider, MyCorsPolicyProvider>();
    ....
}
```

**Comment by snapbatch** [comment]
@pranavkm thanks all set.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
