### ISSUE TITLE
CORS on Azure WebApp

### ISSUE THREAD

**Issue by Asesjix** [aspnet/CORS#39]
When I use CORS in a WebApp Azure, this is ignored. 
The only thing that takes is a Web.config in "wwwroot". 
Am I doing here an error or is this a bug?

ConfigureServices
```
            services
                .AddMvcCore()
                .AddViews()
                .AddCors(options =>
                {
                    options.AddPolicy("Default", builder =>
                    {
                        builder.AllowAnyHeader();
                        builder.AllowAnyMethod();
                        builder.AllowCredentials();

                        builder.WithOrigins("myapp.azurewebsites.net");                   
                    });
                })
                .AddJsonFormatters(j => j.ContractResolver = new CamelCasePropertyNamesContractResolver());
```
Configure
```
app.UseCors("Default");
app.UseMvc();
```

**Comment by Eilon** [comment]
@Asesjix can you explain what you're seeing that doesn't work? Are you getting an error?

**Comment by Asesjix** [comment]
I get the normal "CORS origin" error.
A solution only bring the adaptation of Web.config.
However, then work indeed GET operations but at a post I always get NULL.
Although then function GET operations, POST operations, I always get NULL in the controller.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <system.webServer>
   <httpProtocol>
     <customHeaders>
       <add name="Access-Control-Allow-Origin" value="myapp.azurewebsites.net" />
     </customHeaders>
   </httpProtocol>
 </system.webServer>
</configuration>
```

**Comment by Eilon** [comment]
@kichalla can you take a look?

**Comment by Asesjix** [comment]
I will try to provide a sample project, but I do not know when I have time for.

**Comment by kichalla** [comment]
@Asesjix What happens if you remove the line `app.UseCors("Default");`?

**Comment by davidfowl** [comment]
WithOrigins normally includes the scheme doesn't it?

**Comment by davidfowl** [comment]
e.g.
```
builder.WithOrigins("http://myapp.azurewebsites.net");                   
```

**Comment by kichalla** [comment]
:+1:  on what @davidfowl mentioned

**Comment by Asesjix** [comment]
I'm sorry guys. The scheme was included in my code, missing only in my post. This was also not the fault but the configuration for the handler in the web.config. The Web.config must be lost in a commit. I found the bug when creating a [sample application](https://github.com/Asesjix/AspNet/commit/aec6fdcb709078628bd10a1f80e45b21fe947089) ;-)
``` 
  <system.webServer>
    <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
  </system.webServer>
```
