### ISSUE TITLE
API review updates for CORS

### ISSUE THREAD

**Issue by Eilon** [aspnet/CORS#41]
In particular, a lot of types need to move out of the `Cors.Core` namespace. The main `Cors` namespace should have the most commonly used types, and plumbing can go into a sub-namespace.

**Comment by Eilon** [comment]
Met with @kichalla @rynowak and @danroth27 with these conclusions:

- [ ] Merge both packages into `Microsoft.AspNet.Cors`. 
 - The current package separation in practice provided very little value, and unfortunately was self-defeating with respect to the original purpose of having two packages: to encourage developers using MVC to use just the parts MVC needed. Unfortunately it was most common to reference the both packages transitively anyway (which was harmless, but unnecessary)
- [ ] Move `DisableCorsAttribute` and `EnableCorsAttribute` into `.Cors` namespace
- [ ] Move all other types from both original assemblies (including `CorsMiddleware` and `CorsPolicyBuilder`) into `.Infrastructure` namespace.
- [ ] Post announcement that links back to this issue

**Comment by davidfowl** [comment]
Nice
