### ISSUE TITLE
Preflight request seems to require authentication (beta7)

### ISSUE THREAD

**Issue by sandorfr** [aspnet/CORS#45]
It appears that preflight requests require authentication. I'm currently using the bearer token middleware. Chrome does not provide the credentials when issuing preflight request but if I don't provide the authorization header, the preflight (OPTIONS) fails with 401. ( I tried with and without AutomaticAuthentication). 

So I guess this is a configuration issue. I tried to move AddCors to the very beginning of ConfigureServices and played with (Dis)AllowCredentials without any luck.

```
 services.AddCors();
            services.ConfigureCors(options =>
            {
                options.AddPolicy("api", builder => builder
                .AllowAnyOrigin()
                //.AllowAnyHeader()
                .WithHeaders("accept", "accept-encoding", "accept-language", "X-Requested-With", "authorization", "applicationToken", "content-type", "time-zone-offset", "api-version")
                .WithMethods("GET", "PATCH", "PUT", "DELETE", "POST")
                .WithExposedHeaders("new-authentication-token"));
            });
```

**Comment by davidfowl** [comment]
The order is only relevant in Configure not ConfigureServices

**Comment by DAllanCarr** [comment]
Im not sure if this is chrome specific behaviour with AllowAnyOrigin.
http://stackoverflow.com/questions/19743396/cors-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-i

**Comment by sandorfr** [comment]
@davidfowl this was what I thought but I tried anyway.

@DAllanCarr  Actually it appears that the chrome behavior is correct. "Additionally, for credentialed HTTP requests it needs to be opt-in to prevent leaking potentially-sensitive data." : https://fetch.spec.whatwg.org/#preflight-request

The issue seems to be with either CorsMiddleware which should intercept OPTIONS before authentication or the authentication middlewares which should ignore OPTIONS request (or at least provide an options to do so).

**Comment by DAllanCarr** [comment]
Have you disabled authorization on the server just to check the preflight response.

**Comment by ChristianLegault** [comment]
Having same issue trying to use OAuthBearerAuthentication. Disabling authorizations as no effect.

**Comment by DAllanCarr** [comment]
Step is to know why it is preflighting which in this case is due to the authorization header being sent.

**Comment by danroth27** [comment]
@sandorfr Can you show us what your Configure method looks like?

**Comment by kichalla** [comment]
+1 @sandorfr could you share how your Configure method looks like?

**Comment by Eilon** [comment]
@sandorfr can you share more of your app?

**Comment by sandorfr** [comment]
@Eilon  sorry I'm had too much on my plate and had to workaround the issue but I just migrated to beta8. I'll verify that it is still occuring and provide a repro project during the weekend.

**Comment by Eilon** [comment]
Thanks!

**Comment by kichalla** [comment]
I am able to repro this scenario. More info below:

1. Following was the preflight request which I tried with
```
OPTIONS http://localhost:5000/ HTTP/1.1
Accept: text/json
Host: localhost:5000
Origin: http://foo.example
Access-Control-Request-Method: POST
Access-Control-Request-Headers: BLAH
```

2.
Cors config
```
services.AddCors(o =>
{
    o.AddPolicy("policy1", cpb =>
    {
        cpb.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin().AllowCredentials();
    });
});
```
On my controller
```
[EnableCors("policy1")]
[TestAuthorizationFilter]
public class HomeController : Controller
{
```

Test auhorization filter (this blindly sets the result here causing authorization to fail):
```
public class TestAuthorizationFilter : Attribute, IAuthorizationFilter
{
    public void OnAuthorization(AuthorizationContext context)
    {
        context.Result = new ContentResult() { Content = "You are not authorized!!", StatusCode = 401 };
    }
}
```

**Result**: When I send the above preflight request, the above test authorization filter kicks in and I get a 401

As a workaround I used the CorsMiddleware (even though ideally this should not be required as MVC should be able to handle it).
3.
```
app.UseCors("policy1");
```

Result: I get the result as expected (this is not surprising as this middleware runs even before MVC pipeline kicks in)
```
HTTP/1.1 204 No Content
Date: Tue, 03 Nov 2015 21:41:29 GMT
Server: Kestrel
Vary: Origin
Access-Control-Allow-Origin: http://foo.example
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: BLAH
```

**Comment by dallancarr** [comment]
👍

**Comment by kichalla** [comment]
85080ae621193f3bdd10eb83b1141b0809ea5e17
