### ISSUE TITLE
Missing null check in CorsPolicyBuilder

### ISSUE THREAD

**Issue by wouterdevinck** [aspnet/CORS#51]
The Combine method in in CorsPolicyBuilder is missing a null check on policy.PreFlightMaxAge: https://github.com/aspnet/CORS/blob/dev/src/Microsoft.AspNet.Cors/CorsPolicyBuilder.cs#L183

**Comment by Eilon** [comment]
@wouterdevinck nice catch!

@kichalla please make sure to add a test for this as well.
