### ISSUE TITLE
CORS rc1-final - Not working

### ISSUE THREAD

**Issue by Fosol** [aspnet/CORS#55]
My CORS configuration no longer appears to work in rc1-final.  None of my responses are including the headers for ACCESS-CONTROL.

Did something change in rc1-final?

**Comment by buraktamturk** [comment]
It does work. It requires additional step to work like using app.UseCors() while configuring the services. Previously, app.AddCors() were enought.

**Comment by Fosol** [comment]
I'll have to take your word for it until I can find more time to test.
```
           services.AddCors();
```
and
```
            app.UseCors(options =>
            {
                options.AllowAnyHeader();
                options.AllowAnyMethod();
                options.AllowAnyOrigin();
            });
```
For some reason nothing was coming back with headers.

Thanks for responding though.

**Comment by singlewind** [comment]
Hi @Fosol, I have exact same issue as you had. I tried a vanilla project and could not get it work.
