### ISSUE TITLE
Cors requires authorization on preflight

### ISSUE THREAD

**Issue by Tratcher** [aspnet/CORS#60]
_From @shederman on January 8, 2016 7:11_

The W3 spec clearly states that this should not be the case.

```
Request:
Request URL:http://localhost:2116/releases
Request Method:OPTIONS
Status Code:401 Unauthorized
Remote Address:[::1]:2116
Response Headers
view source
Content-Length:0
Date:Fri, 08 Jan 2016 06:56:49 GMT
Server:Kestrel
X-Powered-By:ASP.NET
X-SourceFiles:=?UTF-8?B?QzpcUHJvamVjdHNcT2N1bHVzXHNyY1xPY3VsdXMuUmVsZWFzZS5BcGlcd3d3cm9vdFxyZWxlYXNlcw==?=
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Access-Control-Request-Headers:accept, authorization
Access-Control-Request-Method:GET
Cache-Control:max-age=0
Connection:keep-alive
Host:localhost:2116
Origin:http://localhost:17185
Referer:http://localhost:17185/rel
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
```

_Copied from original issue: aspnet/Security#648_

**Comment by Tratcher** [comment]
_From @shederman on January 8, 2016 7:14_


			services.AddCors(options =>
			{
				options.AddPolicy("CorsPolicy", builder =>
				{
					builder.AllowAnyHeader()
					.AllowAnyMethod()
					.AllowAnyOrigin()
					.AllowCredentials();
				});
			});


			app.UseCors("CorsPolicy");

**Comment by Tratcher** [comment]
_From @davidfowl on January 8, 2016 8:29_

/cc @kichalla

**Comment by Tratcher** [comment]
_From @blowdart on January 12, 2016 12:6_

This is a CORS bug. Please recreate the issue in the CORS repo. 

https://github.com/aspnet/CORS

**Comment by DavidsonA** [comment]
Is there a workaround for this until RC2? I am working on a web api with Windows authentication and cross-domain javascript clients and have found this issue to block development or deployment.

**Comment by dougbu** [comment]
@DavidsonA or @shederman, how is CORS configured in your failing application?

I can see the preflight request appears valid and the response shows nothing CORS-related has run. But I can't tell _why_ without more information. For example, does the application use the CORS middleware or the MVC bits?

Breaking up original code block for future reference...
Request:
```
Request URL:http://localhost:2116/releases
Request Method:OPTIONS
```

Request headers:
```
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Access-Control-Request-Headers:accept, authorization
Access-Control-Request-Method:GET
Cache-Control:max-age=0
Connection:keep-alive
Host:localhost:2116
Origin:http://localhost:17185
Referer:http://localhost:17185/rel
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
```

Response:
```
Status Code:401 Unauthorized
Remote Address:[::1]:2116
```

Response headers:
```
Content-Length:0
Date:Fri, 08 Jan 2016 06:56:49 GMT
Server:Kestrel
X-Powered-By:ASP.NET
X-SourceFiles:=?UTF-8?B?QzpcUHJvamVjdHNcT2N1bHVzXHNyY1xPY3VsdXMuUmVsZWFzZS5BcGlcd3d3cm9vdFxyZWxlYXNlcw==?=
```

**Comment by DavidsonA** [comment]
@dougbu I have CORS configured in this manner:


    services.AddCors(x => x.AddPolicy("allowall", new CorsPolicy
            {
                Origins = { "http://localhost:3000", "http://localhost:24899" },
                Headers = { "*" },
                Methods = { "*" },
                SupportsCredentials = true,
            }));


    app.UseCors("allowall");

Both of the above blocks run before any other statements in Configure() and ConfigureServices()

I also have anonymous authentication disabled, windows authentication enabled. On the client I'm attempting to POST some json data which triggers the preflight request which has no authentication headers:

    $.ajax({
      dataType: "json"
      , type: "POST"
      , contentType: "application/json"
      , url: "http://localhost:8000/Api/example"
      , data: JSON.stringify(exampleData)
      , success: () => console.log("success")
      , error: () => console.log("failure")
      , xhrFields: {
        withCredentials: true
      }
    });

I may be able to put an example project as I'm a bit stuck until this is sorted or worked around. As best as I understand, if an OPTIONS request is generated CORS should respond to it before the request is rejected due to lack of authentication headers.

**Comment by DavidsonA** [comment]
@dougbu I've created a repro for this issue: https://github.com/DavidsonA/cors-19-repro

If you download that repro, set both ExampleClient and ExampleApi to run, then navigate to localhost:8001 you'll see the issue in the developer console.

**Comment by dougbu** [comment]
@DavidsonA thanks for the repro. I'm having a look...

**Comment by DavidsonA** [comment]
Thanks. For anyone else depending on this ticket I've found a workaround (for development only) on Chrome:

1. Close all Chrome windows
2. Confirm all Chrome processes are terminated
3. Launch Chrome with the following command line arguments: "--args --disable-web-security"
4. If you see a yellow banner warning about insecure and unsupported settings, your browser session won't do any CORS validation so you won't experience the issue described in this task.

This is obviously just to allow you to continue work on your dev machine.

**Comment by dougbu** [comment]
I can reproduce this problem when using the `launchSettings.json` in your `ExampleApi` project. However that file starts out strangely (abridged but changed to valid JSON):
``` json
{
  "iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false
  }
}
```

If `"anonymousAuthentication"` is not enabled, the preflight request (which always lacks authentication) cannot reach the application (the CORS middleware in particular). Change that line to `"anonymousAuthentication": true` and all looks well.

I believe the default setup starts with
``` json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true
  }
}
```

Did you see a recommendation in our documentation to use `"anonymousAuthentication": false` when switching to `"windowsAuthentication": true`? I'd like to be sure we're not making recommendations that lead to this failure.

/cc @blowdart

**Comment by blowdart** [comment]
Windows authentication is all or nothing and is taken care of by IIS before ASP.NET even runs.

It's not compatible with cors, that's just the way it works.

**Comment by Tratcher** [comment]
Actually, we can mix anonymous and windows, so long as you configure authorization on your controllers.
```
{
  "iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": true
  }
}
```
See https://github.com/aspnet/IISIntegration/blob/1.0.0-rc1/src/Microsoft.AspNet.IISPlatformHandler/AuthenticationHandler.cs#L54

**Comment by dougbu** [comment]
@DavidsonA and @shederman I got a quick demonstration of this working for the simple "require an authenticated user" scenario. According to aspnet/Home#1232 and aspnet/Common#85, more advanced policies in RC1 involving Windows authentication will likely hit problems.

Good news is that I can debug and observe the following
```
User.Identity.Name
"REDMOND\\dougbu"
User.Identity.IsAuthenticated
true
User.Identity.AuthenticationType
"Negotiate"
```

Only required changes are the `"iisSettings"` settings @Tratcher mentioned and the following `Startup` replacement for `AddMvc()`:
``` c#
            services.AddMvc(config =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                config.Filters.Add(new AuthorizeFilter(policy));
            });
```

VS also changed the `web.config` file to include `forwardWindowsAuthToken="true"`.

@DavidsonA I'll push a PR to your repo (or clone my version) to make this a bit more concrete.

**Comment by DavidsonA** [comment]
Thanks everyone, that worked for me.

@dougbu I enabled windows authentication and disabled anonymous authentication on my own accord , I did not see anything of that nature in the documentation so no error at your end.

Thanks again and good luck over the coming months. Looking forward to the aspnet core release.

**Comment by SamiAl90** [comment]
Hey all,

I am suffering the same problem at this moment. I did as @Tratcher described and also as @dougbu said. It works now but that solution is really "hacky" in my opinion. Is there some better way to do so now? Since the last post is from the first of february.

Kind regards and thanks in advance.

**Comment by dougbu** [comment]
@SamiAl90 if you dislike changing launch settings, please file a new issue describing your specific concerns. For example, what should be easier to do and how would you prefer to do it?

**Comment by SamiAl90** [comment]
@dougbu I didn't say that I don't like the launch settings those are not a problem. I was just wondering if there is a better way to allow cross site origins with windows authentification so I won't need to send the xhr field on every request I want to do from the front-end.

**Comment by dougbu** [comment]
> so I won't need to send the xhr field on every request I want to do from the front-end

Nothing about the CORS headers has changed recently.

**Comment by e5enrico** [comment]
For anyone else struggling with this; I managed to get CORS and Windows Auth working in Chrome with dotnetcore by allowing both WindowsAuthentication and AnonymousAuthentication and them in the 1st middleware I check for authentication for all methods except OPTIONS (Preflight) and return a 401 where appropriate.

Middleware:
```javascript
       private_ async void BeginInvoke(HttpContext context)
        {
            if (context.Request.Method!="OPTIONS" && !context.User.Identity.IsAuthenticated)
            {
                context.Response.StatusCode = 401;
                await context.Response.WriteAsync("Not Authenticated");
            }
        }
```

I have a repo here which demonstrates the problem in the initial checkin and then the fix as the last checkin:
https://github.com/e5enrico/CoreWebApp/

jsFiddle to do the CORS calls:
http://jsfiddle.net/enricosaunders/o2u3yete/

**Comment by drano** [comment]
When enable anonymous and windows authentication, CORS Pre-Flight works correctly, but I have an 500 error code on my GET method (without error message). This method should use Windows authentication.

Any ideas ?

**Comment by Tratcher** [comment]
Logging?

**Comment by drano** [comment]
I deactivates logging, but the problems remains. The first call is anonymous, then why the second method should ask for a challenge Kerberos/Windows Authentication ?

**Comment by e5enrico** [comment]
Drano - If you are using the code I posted above the error could be due to the fact that the pipeline is not interrupted and something else may be trying to write to the context.Response.

Change the code slightly to stop the pipeline:
```javascript
public async Task Invoke(HttpContext context)
        {
            if (context.Request.Method != "OPTIONS" && !context.User.Identity.IsAuthenticated)
            {
                context.Response.StatusCode = 401;
                return; //Stop pipeline and return immediately.
            }
            await _next(context);
        }
```

**Comment by SamiAl90** [comment]
@drano add this policy as written above in your mvc options

` 
services.AddMvc(options => {
....
 var policy = new AuthorizationPolicyBuilder()
.RequireAuthenticatedUser()
.Build();
options.Filters.Add(new AuthorizeFilter(policy));
...
}
`
+ enable windows auth + anonymous auth for IIS Launchsettings
This will alow the user to enter the startup file without being authentificated but for controller / controller actions you will need to be authentificated

**Comment by amivit** [comment]
After hours and hours of pain I finally pin-pointed the issue being that pesky OPTION request (understandingly) not including the authorization header (which explains why everything worked in my 3rd party REST-client - not the browser)... Which then allowed me to further Google my way to this thread. THANKS SO MUCH GUYS. 

One last detail: having both anonymous and Windows authentication gave me a new problem: "No authenticationScheme was specified, and there was no DefaultChallengeScheme found."

The fix: https://stackoverflow.com/a/45818096/865744

**Comment by arufolo** [comment]
@drano I'm having the same exact issue you were. Preflight now working, but 500 on the subsequent POST. Were you ever able to find a solution to your issue?
