### ISSUE TITLE
Resource sent to unauthorized origin

### ISSUE THREAD

**Issue by rms81** [aspnet/CORS#61]
Hi,
I´ve noticed that in a MVC 6 app, using CORS, when a request is made from a unauthorized origin, the header  "Access-Control-Allow-Origin" is, as expected, not set, but the response status code 200 and the resource is sent in the response body. I was wondering, that if the resource cannot be shared, it should not be sent across the wire. I was expecting that the request would not event hit the Controller.

Is this behavior correct? 

Thank you

**Comment by brockallen** [comment]
Yes, this is the correct behavior. It's left up to the browser to prevent the calling JS from receiving the response payload. 

If you require authorization to the resource, then enforce that (in addition, yet orthogonal to CORS) by requiring authentication of some sort.

**Comment by Eilon** [comment]
Indeed, I believe that the nature of CORS is that both the client and server need to be trusted to implement both sides of the protocol correctly. The server may very well send some data to the *browser*, but the browser will ensure that the *app* won't receive the data.

**Comment by rms81** [comment]
Ok. Being CORS something more browser related its up to the browser to take care of most part of the implementation details.
Thank you for your answers.
