### ISSUE TITLE
Not Understanding CORS

### ISSUE THREAD

**Issue by Fosol** [aspnet/CORS#63]
I've configured and enabled CORS in my Startup.  Yet when I run my test application not one single static file includes the headers.  Chrome continues to post errors about it, but IE is just happy.

Is there something I'm not understanding?

**Comment by RehanSaeed** [comment]
+1 Same Here.

**Comment by Eilon** [comment]
@Fosol can you show more about what you did, what you were expecting, and what the results were? E.g. startup code / config, exact scenario you tried, and perhaps network trace of what happened? A bit difficult to diagnose this type of issue with limited info.

**Comment by Fosol** [comment]
I'll try and provide an example application by the end of the week.  Swamped in work atm.

**Comment by allenmoatallen** [comment]
I seem to be experiencing the same issue, can't seem to get the CORS headers returned. I'll provide my Startup.cs

```cs
public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddLogging();
            
            services.AddCors(options =>
                options.AddPolicy("AllowAll", p => p.AllowAnyOrigin()
                                                   .AllowAnyMethod()
                                                   .AllowAnyHeader()));
            services.AddMvc();

            services.AddInstance<IDbContext>(new SchedulingContext(Configuration["Data:DefaultConnection:ConnectionString"]));

            // Register services
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();

            var builder = new ContainerBuilder();
            builder.RegisterAssemblyTypes(assemblies)
                .Where(t => t.GetInterfaces()
                .Any(i => i.IsAssignableFrom(typeof(IEventHandler<>))))
                .AsImplementedInterfaces()
                .InstancePerDependency();

            builder.RegisterType<ScheduleRepository>().As<IScheduleRepository>().InstancePerDependency();
            builder.RegisterType<FacilitySettings>().As<IApplicationSettings>().InstancePerDependency();

            builder.Populate(services);

            var container = builder.Build();

            return container.Resolve<IServiceProvider>();
        }
```

and

```cs
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(minLevel: LogLevel.Verbose);

            app.UseIISPlatformHandler();

            app.UseDeveloperExceptionPage();
            
            app.UseCors("AllowAll");
            app.UseMvcWithDefaultRoute();
        }
```

I just have a simple GET method in my API controller.

**Comment by khellang** [comment]
You're not sending an `Origin` header. By default, most browsers don't send this header for same-origin requests.

Take a look at this flow diagram to get a feel for how CORS works:

![CORS Flow](http://www.html5rocks.com/static/images/cors_server_flowchart.png)

**Comment by allenmoatallen** [comment]
@khellang I noticed that as well, here is the updated screen showing I am sending one with the same behavior:

![2016-03-03_7-27-52](https://cloud.githubusercontent.com/assets/2071929/13497241/8d33c7fc-e111-11e5-9cfc-b9fd72656205.jpg)

You can see in the bottom I am sending an Origin header but still no CORS response from Kestrel/.NET

**Comment by allenmoatallen** [comment]
Thanks!

**Comment by Eilon** [comment]
Closing for now because we don't have enough information.
