### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by RodrigoAxel** [aspnet/CORS#68]
Hi,

Using a newly generated RC1 project from visual studio, adding Cors as described by the oficial documentation (https://docs.asp.net/en/latest/security/cors.html) seems to not work.

**project.json (all of it):**
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.AspNet.Cors": "6.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}

**Startup.cs:**
public void ConfigureServices(IServiceCollection services)
{
    // Add framework services.
    services.AddCors();
    services.AddMvc();
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(Configuration.GetSection("Logging"));
    loggerFactory.AddDebug();

    app.UseIISPlatformHandler();

    app.UseStaticFiles();

    app.UseCors(builder =>
        builder
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowAnyOrigin()

    );

    app.UseMvc();
}
       

**Outputs the following headers:**
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Server: Kestrel
X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNcQXhlbE1cRGVza3RvcFxXZWJBcHBsaWNhdGlvbjFcc3JjXFdlYkFwcGxpY2F0aW9uMVx3d3dyb290XGFwaVx2YWx1ZXM=?=
X-Powered-By: ASP.NET
Date: Tue, 01 Mar 2016 07:17:50 GMT
Content-Length: 19

**Comment by halter73** [comment]
Can you include the request headers?

**Comment by RodrigoAxel** [comment]
My error, everything is working as expected, I wasn't including the 'Origin' header (this header is needed to trigger Cors).

Sorry for the inconvenience.
