### ISSUE TITLE
Cannot find documentation/examples of how to support wildcard subdomains

### ISSUE THREAD

**Issue by sjdirect** [aspnet/CORS#75]
Below is what i have posted on  [stackoverflow](http://stackoverflow.com/questions/36877652/configure-cors-to-allow-all-subdomains-using-asp-net-core-asp-net-5-mvc6-vnex) regarding this issue... 

I have cors setup correctly in an ASP.NET Core web app. Im using the following package...

```
"Microsoft.AspNet.Cors": "6.0.0-rc1-final"
```

and here is the startup.cs snippet...

```
public virtual IServiceProvider ConfigureServices(IServiceCollection services)
{
    services.AddCors
    (
        options =>
        {
            options.AddPolicy
            (
                CORSDefaults.PolicyName, 
                builder =>
                {
                    //From config...
                    var allowedDomains = new []{"http://aaa.somewhere.com","https://aaa.somewhere.com","http://bbb.somewhere.com","https://bbb.somewhere.com"};

                    //Load it
                    builder
                        .WithOrigins(allowedDomains)
                        .AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowCredentials();
                }
            );
        }
    );
}
```

This works great except that the list of subdomains to allow is growing fast and I want to allow all subdomains of "somewhere.com". Something like "*.somewhere.com". I cant seem to find any documentation on how to do this in the new ASP.NET Core (MVC6, ASP.NET5, VNext). All the docs/examples I'm finding that demonstrate how to do this are for earlier versions of MVC or WebApi. How can I achieve this in the new stack?

**Comment by sjdirect** [comment]
Submitted this pull request on the master branch...

https://github.com/aspnet/CORS/pull/76

**Comment by blowdart** [comment]
I don't believe it is supported.

**Comment by rynowak** [comment]
@blowdart - I think the question is **should** we support it... If I'm missing something can you provide more info?

**Comment by blowdart** [comment]
I saw the PR. It feels wrong from a security perspective, the CORS spec doesn't mention wildcards at all, you ought to list all your domains, especially when you know someone will whitelist azurewebsites.net because they don't understand the risks.

However it does make everything easier, so from a user PoV it's a good thing.

Do rails et al support wildcards?

**Comment by sjdirect** [comment]
@blowdart, what if I wanted to provide an api only to azure users? Without this functionality I'm not sure how it could be done without some heavy initialization costs and data availability from Azure.

**Comment by blowdart** [comment]
I have to admit, exposing a service that loosely fills me with a creeping horror, you might as well open to all, but I do take your point.

@rynowak we should support the scenario. Hopefully no-one would do *.com, but at that point you're shooting yourself in the foot I guess.

**Comment by Eilon** [comment]
Given where we are in the product lifecycle I'm putting this on the backlog for now.

I do like this feature but we are working on product stabilization at this time and doing our best to minimize introducing new features.

**Comment by sjdirect** [comment]
Understood. I have a workaround in place
<http://stackoverflow.com/questions/36877652/configure-cors-to-allow-all-subdomains-using-asp-net-core-asp-net-5-mvc6-vnex/36925805#36925805>
that suits my needs so no pressure from me. Thanks for your time.

**Comment by Eilon** [comment]
@sjdirect thanks for understanding!

**Comment by Choc13** [comment]
Would it be possible to make this more flexible by adding a `Func<string, CorsPolicy, boolean> OriginFilter`  to the `CorsOptions` as part of the `AddCors` extension method. Then in `CorsService` add

```
private bool IsOriginAllowed(string origin, CorsPolicy policy)
{
    return !string.IsNullOrWhiteSpace(origin) &&
                (policy.AllowAnyOrigin ||
                 policy.Origins.Contains(origin) ||
                 (_corsOptions.OriginFilter != null && _corsOptions.OriginFilter(origin, policy)));
}
```

By Then provide a default implementation of the wildcard subdomain origin matcher using code similar to that in @sjdirect's StackOverflow post. As I imagine most people would be looking to use this to add that behaviour. So in that case they could just do this when adding cors:

```
services.AddCors(options => options.OriginFilter = CorsOptions.SubdomainWildcardFilter);
```

Happy to put together a PR if this of interest.

**Comment by wparad** [comment]
Please just take a function, you don't need to worry about "security concerns" let developers to their thing.  Most know what is good and bad, but when they want to do the bad thing anyway, they will find away.  Why not make it straight forward here, wildcards are really common pattern, and if allow all, why not allow some?  I don't thing security even comes into play, if it did, we should probably remove the AllowAllOrigns from the library as well.

**Comment by Choc13** [comment]
Agree with @mharthoorn in #89 that this should actually be applied on a per policy basis rather than for the entire `CorsService`

**Comment by Eilon** [comment]
We will consider this for the next version.

**Comment by Eilon** [comment]
We merged https://github.com/aspnet/CORS/pull/94, so closing this.
