### ISSUE TITLE
Make HTTP method match as case-insensitive

### ISSUE THREAD

**Issue by rynowak** [aspnet/CORS#77]
I know the spec says that HTTP methods are case-sensitive - but don't we do this other places?

https://github.com/aspnet/CORS/blob/dev/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsMiddleware.cs#L103

**Comment by davidfowl** [comment]
We should not, we should be case insensitive where we can.

**Comment by rynowak** [comment]
> We should not, we should be case insensitive where we can.

`Error CS1092: Statement ambiguous`

**Comment by davidfowl** [comment]
I misread the link, we should be case insensitive and fix this code 😄

**Comment by rynowak** [comment]
Are you saying we should change the other stuff?

**Comment by davidfowl** [comment]
It should be case insensitive across the board

**Comment by Tratcher** [comment]
Agreed, case insensitive.

**Comment by Eilon** [comment]
@Tratcher are there other areas where we are not case-sensitive, but should be?

**Comment by Eilon** [comment]
Moving to post-RTM.
