### ISSUE TITLE
CORS does not works after enable JWT bearer token

### ISSUE THREAD

**Issue by liupengf12** [aspnet/CORS#80]
I use JWT bearer token in my web api project and the codes like this:

````C#
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
app.UseJwtBearerAuthentication(new JwtBearerOptions
{
    Authority = appSettings.Value.IdentityServerUrl,
    RequireHttpsMetadata = false,
    AutomaticAuthenticate = true
});
````

And the CROS settings like this:

````C#
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAllOrigins", policyBuilder =>
                {
                    policyBuilder
                    .AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader();
                });
            });
````

````C#
            app.UseCors("AllowAllOrigins");
````

The requests:
![image](https://cloud.githubusercontent.com/assets/117811/16229912/87f0a580-37f1-11e6-9cac-31fea1c12583.png)
![image](https://cloud.githubusercontent.com/assets/117811/16229951/b8a8214e-37f1-11e6-9261-5ef63703c48b.png)

Why the response of first OPTION request contains Access-Control-Allow-Origin:*
But the second GET request does not contain Access-Control-Allow-Origin:* ?

I use angularjs to call the API:
````javascript
  function authInterceptorService($q, $location, $injector, config, localStorageService, _) {
      var service = {
        responseError: _responseError,
        request: _request,
      };

      var apiUrl = config.API_URL;

      return service;
      /////////////

      function _request(config) {
        var access_token = localStorageService.get('access_token');

        config.headers = config.headers || {};
        if (access_token && _.startsWith(config.url, apiUrl) && (!_.startsWith(config.url, apiUrl+'/token') || !_.startsWith(config.url, apiUrl+'/sendcode'))) {
          config.headers.Authorization = 'Bearer '+ access_token;
        }

        return config;
      }
````

If not set the authorization header, the same request like this:
![image](https://cloud.githubusercontent.com/assets/117811/16230164/bfcc0138-37f2-11e6-9ec5-afb7d87798af.png)

**Comment by rynowak** [comment]
The response to your second request is a 500 of content-type text/html - is this coming from an error handler rather than your API?

**Comment by liupengf12** [comment]
@rynowak Your are right, there is a internal error, after fixed that error it works well.
Thanks.

**Comment by mariapaulinar** [comment]
Can you share your solution? I have same problem, I've tried a lot of things and it still comes up in some requests :( Thanks.

**Comment by rynowak** [comment]
@mariapaulinar in that case I believe he was enountering another error somewhere else in his code. Can you please open a new issue and describe the problem you are having?
