### ISSUE TITLE
Session is not working on IIS with CORS

### ISSUE THREAD

**Issue by muratg** [aspnet/CORS#81]
_From @devilsuraj on June 28, 2016 8:19_

I am using sessions to manage application state in ASP.NET CORE and it's configured as below.

```
 services.AddSession(options =>
            {
                options.CookieName = ".my.Session";
                options.IdleTimeout = TimeSpan.FromSeconds(20);
            });
```
It's working on localhost but on remote IIS 8 it's not creating cookies so not able to get the values. I also have enabled CORS and don't know what exactly caused this problem. In log it's not showing error either. It's creating session getting stored id but no cookie at client side.

_Copied from original issue: aspnet/Session#118_

**Comment by muratg** [comment]
_From @kichalla on June 28, 2016 16:36_

Could you share a sample repro project?

**Comment by muratg** [comment]
_From @devilsuraj on June 28, 2016 19:23_

thanks for reply i am following this https://github.com/aspnet/MusicStore 
this is the code where session is created  
```
private static string GetCartId(HttpContext context)
        {
            var cartId = context.Session.GetString("Session");

            if (cartId == null)
            {
                //A GUID to hold the cartId. 
                cartId = Guid.NewGuid().ToString();

                // Send cart Id as a cookie to the client.
                context.Session.SetString("Session", cartId);
            }

            return cartId;
        }
```
but tis not working on CORS i am getting cookie in response header but its not set in browser .
everytime it just send me new set cookie in response header , the cookie is never set ,it may be stupid to ask but i am not sure, is it cors related or i have add any cookiedomain or something so it can work with any domain... I am also using angular2 as client

**Comment by muratg** [comment]
_From @Tratcher on June 28, 2016 22:53_

What is your CORS policy? Some CORS policies do not allow cookies.

**Comment by muratg** [comment]
_From @devilsuraj on June 28, 2016 23:14_

@Tratcher as for now i have allowed everything in CORS , anyways after researching a lot i found cookies wont work on cross domain for security reasons. anyways i will get the app on subdomain , will test and close the issue

**Comment by muratg** [comment]
_From @devilsuraj on June 28, 2016 23:30_

well its not working on subdomains either this is the response header
Set-Cookie:.mysession.Session=e506554c-34b1-8990-de71-a9d12cd4a3ff; domain=.mydomain.com; path=/; httponly

my session config
 ```
services.AddSession(options =>
            {
                options.CookieName = ".mysession.Session";
                options.IdleTimeout = TimeSpan.FromSeconds(20);
                options.CookieDomain = ".mydomain.com";
                           });
```

my CORS policy
```
 services.AddCors(options =>
            {
                options.AddPolicy("AllowndSTFU",
                    builder => builder.AllowAnyOrigin()
                                     .AllowAnyMethod()
                                     .AllowCredentials()
                                    .AllowAnyHeader());
            });
```

its generating cookie from backend.mydomain.com and   i need to access it on app.mydomain.com

**Comment by muratg** [comment]
_From @Tratcher on June 29, 2016 17:25_

(not directly related, but it looks like you're still using RC2, you should move to 1.0).

**Comment by devilsuraj** [comment]
i updated to 1.0 i think its just Id is not opaque now but its not working with domain name
`Set-Cookie:.swapKart.Session=CfDJ8BRCECbMEPVJohJqV5kdf0FLqOw6ICpUMnv%2BC0YsNjAEHsfYe7XkQUuxpwsqKKZeiti1yKdNtDnxEy%2Fms3hdfBVB62fj4XJFHchAv1H3TKALF8RDGj0SKZZZj9VkSxD3rXoROxDYygv79uf%2B2gBp40q%2BJJCwVTaj%2BTU5XG55%2Bzgx; domain=mydomain.com; path=/; httponly`

however any update on issue??

**Comment by muratg** [comment]
cc @Eilon

**Comment by prasannapattam** [comment]
With "Passing Credentials in Cross-Origin Requests" option, I was able to have the session in CORS over IIS. I am using the option mentioned in this link
http://www.asp.net/web-api/overview/security/enabling-cross-origin-requests-in-web-api#credentials

**Comment by Eilon** [comment]
@kichalla can you continue investigating this? Do we think there's a bug here?

**Comment by kichalla** [comment]
I tried this scenario on IIS and using the article @prasannapattam had shared but for .NET Core. I was not able to repro the issue. 

My verification steps:
- I created couple of `hosts` file entries for `app.mydomain.com` and `backend.mydomain.com` both pointing to `127.0.0.1`
- Added site bindings for the above entries in IIS's website
- Published the ASP.NET Core site to IIS. The idea here is to simulate the scenario where the UI on `app.mydomain.com` is trying to access an api hosted on `backend.mydomain.com` (of course in this case i used the same website for the domain names but i hope this shouldn't matter)

- In Startup.cs
```c#
services.AddSession(o =>
{
    o.CookieDomain = ".mydomain.com";
});

services.Configure<CorsOptions>(options =>
{
    options.AddPolicy("AllowAll",
        builder => builder.WithOrigins("http://app.mydomain.com:8080")
                        .AllowCredentials()
                            .AllowAnyMethod()
                            .AllowAnyHeader());
});
```
- In controller
```c#
    [EnableCors("AllowAll")]
    public class HomeController : Controller
    {
        public IActionResult SetSession()
        {
            HttpContext.Session.SetString("CartId", "10");

            return View(viewName: "Info");
        }

        public IActionResult GetSession()
        {
            return View(viewName: "Info");
        }
    }
```
- In Info.cshtml
```#html
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        function work() {
            $.ajax({
                type: 'get',
                url: 'http://backend.mydomain.com:8080/home/getsession',
                xhrFields: {
                    withCredentials: true
                }
            }).then(function (data) {
                alert(data);
            });
        }
        $.ready(function () {
        });
    </script>
</head>
<body>
    <div>
        Cart id: @Context.Session.GetString("CartId")
    </div>
    <div>
        <button onclick="javascript: work()">Make cross domian request</button>
    </div>
</body>
</html>
```

**Comment by kichalla** [comment]
Closing this issue now. Feel free to re-open if this still does not work for you.
