### ISSUE TITLE
How can we refresh cors Policy after initializing our app?

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/CORS#82]
How can we refresh cors Policy/rules after initializing our app?

**Comment by xrkolovos** [comment]
This might work? 

//new CorsOptions
var options = new CorsOptions();
var policy = new CorsPolicy() { ... };
options.AddPolicy("AllowSpecificOrigin", policy);
//try refresh instance 
services.AddSingleton<IConfigureOptions<CorsOptions>>(new ConfigureOptions<CorsOptions>(configureOptions));

**Comment by Eilon** [comment]
@kichalla any idea if the CORS policies are designed to be updated at runtime? I'm not sure we designed any of this to change at runtime.

**Comment by kichalla** [comment]
A custom [policy provider](https://github.com/aspnet/CORS/blob/1.0.0/src/Microsoft.AspNetCore.Cors/Infrastructure/ICorsPolicyProvider.cs#L20) could be written, which for example could get the policies from a database.

Following articles of ASP.NET Web API 2.0 show examples of Cors and policies in Database. They can give some idea on how to do something similar in ASP.NET Core.

https://msdn.microsoft.com/en-us/magazine/dn532203.aspx
https://blogs.msdn.microsoft.com/webdev/2013/07/02/manage-cors-policy-dynamically/

@Eilon we could probably create a sample for it in Entropy?

**Comment by kichalla** [comment]
I haven't tried this end to end but another possible approach(and probably simpler than database) is to use a configuration file which is watched for changes and policy provider can reload with fresh policies.

For example, when a new Web project is created in VS, the following line in Startup.cs causes the conifguration file to be watched for changes:

```
.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
```

You can update the appsettings.json to include a section for `Cors`. For example, here you can update the Origins node and these changes should be picked up by the custom cors policy provider.

```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "Cors": {
    "Origins": [
      "http://abc.com",
      "http://def.com"
    ]
  }
}
```

**Comment by Eilon** [comment]
@kichalla that will reload the settings, but I doubt that CORS support reloadable settings, so it won't actually do anything.

But it seems that because the custom provider will work, this question is now answered.

**Comment by kichalla** [comment]
> @kichalla that will reload the settings, but I doubt that CORS support reloadable settings, so it won't actually do anything.

Probably I was not very clear, I meant the custom policy provider can watch for the reloadable settings and return the updated policies when asked for.

**Comment by Eilon** [comment]
@kichalla ah sure, yes, custom code can do custom things 😄 But not out-of-the-box with the built-in provider.

**Comment by kbasaris** [comment]
This is a way to refresh origins of an existing policy at runtime

CorsOptions _options;

        public CorsController(IOptions<CorsOptions> options)
        {
            _options = options.Value;
        }

//Begin refresh origin
//here we remove all current origins
options.GetPolicy("AllowSpecificOrigin").Origins.Clear();

//add we add all origins again plus the new ones
foreach (var newOriginin newOrigins){
 _options.GetPolicy("AllowSpecificOrigin").Origins.Add(newOrigin);
}
//End refresh origin

OR if we want just ot add a new origin
 _options.GetPolicy("AllowSpecificOrigin").Origins.Add(newOrigin);

**Comment by rynowak** [comment]
`CorsPolicy` is not thread-safe. You'll get exceptions trying to modify it in a running site. In general data coming from options is assumed to be 'baked' after resolving from DI. Components that consume this data may assume that it won't change.

**Comment by jmurphzyo** [comment]
did anyone ever add an entropy of implementing this?

**Comment by xrkolovos** [comment]
We agree that is something that should be able to change after the app is initialized?

**Comment by kichalla** [comment]
I am working on a sample in Entropy. Will send out a PR soon.

**Comment by kichalla** [comment]
FYI, I checked in the sample now: https://github.com/aspnet/Entropy/commit/1fe770bdafeca53bd094e231d14b780d7810cd03
