### ISSUE TITLE
Security Issue: CORS Mvc auth filter still allows request to execute.

### ISSUE THREAD

**Issue by borgdylan** [aspnet/CORS#88]
As things stand, if ```EnableCorsAttribute``` is used on an MVC action method, the method will still execute and spit out a result over the socket regardless of the CORS test result. The combat this security hole, I had to write an action filter that checks for the ```Origin``` header and see that whenever that header exists in the request, I short circuit the response with a negative status code whenever the CORS authorization filter does not include ```Access-Control-Allow-Origin``` with the requesting origin as part of the outgoing response headers. Please fix this, or make it clear in the docs that a filter like the one I am using must be included in the MVC filter pipeline to avoid leaking data in failed CORS requests.

**Comment by Eilon** [comment]
@borgdylan thanks for the report! Can you provide us with a sample repro app for this? You can email it (or a link to it) to elipton_AT_microsoft_com if it contains any sensitive information.

cc @blowdart 

@kichalla can you take a look at this as well? Please coordinate your investigation with @blowdart until we figure out what's going on here.

**Comment by brockallen** [comment]
This is how CORS works. If you policy doesn't allow the calling origin, then all CORS does is not emit the Access-Control-Allow-Origin response headers. If you want authorization on your endpoint, then implement some security.

**Comment by borgdylan** [comment]
I have implemented security code. I just think that it should be an option in the official package to short circuit the request when CORS validation fails on cross-domain requests.

**Comment by brockallen** [comment]
If you've implemented authorization, then the response would be a 401/403 and then CORS would be moot.

**Comment by borgdylan** [comment]
I am relying on the CORS authorization filter as a signalling step. If there is an "Origin" header in the request I expect an "Access-Control-Allow-Origin" header in the response, else I do not do anything as the request would not be a CORS one.

**Comment by brockallen** [comment]
Perhaps that's your point of confusion -- CORS is a client-side authorization mechanism, not a server-side mechanism.

**Comment by Eilon** [comment]
Yes, @brockallen 's point is critical: CORS from my perspective is about enabling the client (i.e. web browser) to decide which remote calls the web site may make. The browser asks the server for some info in order to make its decision as to what allow the web site to do. (It's a bit more complex than that, of course.)

**Comment by brockallen** [comment]
Also, the server-side CORS plumbing should not prevent the call if Origin is absent. Think about non-browser clients.

**Comment by kichalla** [comment]
Closing this issue as @brockallen is right.
