### ISSUE TITLE
Allow a more flexible AllowOrigin response

### ISSUE THREAD

**Issue by mharthoorn** [aspnet/CORS#89]
Instead of the CorsService peeking into the CorsPolicy

``` csharp
   policy.Origins.Contains(origin)
```

A method `OriginAllowed(string origin)` would allow for a much more flexible lookup policy. The service would then call:

``` csharp
  policy.OriginAllowed(origin)
```

This allows the policy to respond with a more ad hoc response like a (database) lookup.
The default would simply be:

``` csharp
        public virtual bool OriginAllowed(string origin)
        {
            return this.Origins.Contains(origin);
        }
```

But an override policy could become something like: 

``` csharp
        public override bool OriginAllowed(string origin)
        {
            return repository.Exists<Sites>(s => s.Origin == origin);
        }
```

**Comment by Choc13** [comment]
See issue #75

**Comment by Eilon** [comment]
We will consider this for the next version.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2379
