### ISSUE TITLE
Attribute doesn't work with UseCors

### ISSUE THREAD

**Issue by wparad** [aspnet/CORS#91]
Create two policies, useCors on one, and add attributes to controllers for the other.  The attributes won't trigger. A 204 is returned instead.  Adding in an Options method with an attribute on the controller or the actual verb (GET, HEAD, etc...) returns a 200 and the correct headers.

Using this setup:

```
services.AddCors(o =>
{
    o.AddPolicy("AllowAll", builder =>
    {
        builder.AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
    o.AddPolicy("OtherPolicy", builder =>
    {
        builder
            .AllowAnyHeader()
            .AllowAnyMethod()
            .WithOrigins("https://my.special.site.com");
    });
});
```

```
OPTIONS /v1/route/1 HTTP/1.1
    Host: localhost:5001
    Connection: keep-alive
    Pragma: no-cache
    Cache-Control: no-cache
    Access-Control-Request-Method: GET
    Origin: http://localhost:8080
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36
    Access-Control-Request-Headers: accept, authorization
    Accept: */*
    DNT: 1
    Referer: http://localhost:8080/
    Accept-Encoding: gzip, deflate, sdch
```

returns:

```
HTTP/1.1 204 No Content
    Date: Sat, 29 Oct 2016 15:55:39 GMT
    Server: Kestrel
    X-XSS-Protection: 1; mode=block
    Strict-Transport-Security: max-age=31536000
    X-Content-Type-Options: reflected-xss block
```

Instead of:

```
HTTP/1.1 200 OK
    Date: Sat, 29 Oct 2016 15:56:40 GMT
    Content-Length: 0
    Server: Kestrel
    Access-Control-Allow-Headers: authorization
    Access-Control-Allow-Origin: *
    X-XSS-Protection: 1; mode=block
    Strict-Transport-Security: max-age=31536000
    X-Content-Type-Options: reflected-xss block
```

By simply removing the use of `UseCors("OtherPolicy")` and only using the attribute `[EnableCors("AllowAll")]` this works as intended.

**Comment by jbagga** [comment]
CORS can be a little tricky. This may be because you are applying a more restrictive policy `UseCors("OtherPolicy")` and then trying to use a more relaxed version `EnableCors("AllowAll")`. If you wish some controller's actions to be specifically available to a certain origin, apply the more specific policy as an attribute to that controller. Also, when using MVC and CORS, it is recommended you use this [example](https://docs.microsoft.com/en-us/aspnet/core/security/cors#enabling-cors-in-mvc) as a guideline.

Please let me know if the issue is something else. Maybe share your sample application or use the [sample](https://github.com/aspnet/CORS/tree/dev/samples) in the CORS repository to try your scenario.

**Comment by wparad** [comment]
At your link it says
> The precedence order is: Action, controller, global. Action-level policies take precedence over controller-level policies, and controller-level policies take precedence over global policies.

Which directly contradicts what you just said, it seems that documents don't represent the reality, which is "the order of applied policies is global, controller, and then action"

**Comment by dougbu** [comment]
@wparad running the action policies last means they can override (i.e. have precedence over) all other policies. What exactly is incorrect in the documentation?

**Comment by jbagga** [comment]
@wparad Thank you for your response. My apologies. My comment before is not descriptive enough. So, when using `UseCors()` [middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware) logic for Cors runs. This is a completely different middleware than MVC. If you read the [example](https://docs.microsoft.com/en-us/aspnet/core/security/cors#enabling-cors-in-mvc) again, it says

> When using MVC to enable CORS the same CORS services are used, but the CORS middleware is not.

and

> You can enable CORS globally for all controllers by adding the CorsAuthorizationFilterFactory filter to the global filter collection

You are recommended to use CorsAuthorizationFilterFactory to set a global CORS policy for your controllers in MvcOptions. 

This should solve the problem. But let us know if it doesn't work!

**Comment by wparad** [comment]
Thanks @jbagga for the clarifications, let's close the issue for now.
