### ISSUE TITLE
Middleware doesn't return required headers

### ISSUE THREAD

**Issue by wparad** [aspnet/CORS#92]
These headers are never returned:
Access-Control-Allow-Methods
Access-Control-Max-Age

and the status code is 204, and should be 200 (debatable, but it seems like everyone is returning 200 since technically OPTIONS should return a list of allowed methods)

**Comment by jbagga** [comment]
@wparad Can you provide more context to your scenario? Allowing non-simple headers and setting preflight max age in the policy returns the required headers you mentioned, in response to a preflight request. Maybe you can send us the policy you tried to enforce and the request you sent.

@kichalla Could you elaborate on the status code being 204 and not 200?

**Comment by kichalla** [comment]
@wparad The only reason I can think of is that OPTIONS response does not have a body.

**Comment by jbagga** [comment]
@wparad Any updates? Are you still running into this problem? If you can share a quick example, I'd be happy to investigate further.

**Comment by jbagga** [comment]
Closing this issue for now as it cannot be reproduced with the given information. @wparad Please feel free to open it if you encounter it again and provide a quick example of your app.
