### ISSUE TITLE
SimpleRequestHeaders present in Access-Control-Request-Headers are filtered out of response

### ISSUE THREAD

**Issue by StupendousPlatypus** [aspnet/CORS#96]
### Title
SimpleRequestHeaders present in Access-Control-Request-Headers are filtered out of response's Access-Control-Allow-Headers

### Functional impact
MS Edge includes 'accept' within a CORS preflight request. When the preflight response does not include 'accept', Edge will stop the real request.

### Minimal repro steps
[This unit test](https://github.com/aspnet/CORS/blob/46b2d52d7419c9780326af730ea8cd52ccf26d59/test/Microsoft.AspNetCore.Cors.Test/CorsServiceTests.cs#L743) demonstrates the behavior I'm talking about.

### Expected result
When a preflight request is made, the response should contain all headers in the request which are allowed by the CORS policy, not just custom ones.

### Actual result
Some specific headers are being filtered out of the response.

### Further technical details
[The filter in question](https://github.com/aspnet/CORS/blob/46b2d52d7419c9780326af730ea8cd52ccf26d59/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsService.cs#L196).

**Comment by brockallen** [comment]
> MS Edge includes 'accept' within a CORS preflight request. When the preflight response does not include 'accept', Edge will stop the real request.
> When a preflight request is made, the response should contain all headers in the request which are allowed by the CORS policy, not just custom ones.

The spec says that simple request headers are not required to be emitted and browsers should assume they are implied.

**Comment by StupendousPlatypus** [comment]
You're right; sorry for the bad issue.
