### ISSUE TITLE
Improved options for adding policies

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/CORS#99]
I'd love to be able to have the Cors middleware resolve my policies from the container.  If any of my policies require configuration parameters, it seems like there's no nice clean way to break them out into their own files that can depend on `IOptions<Something>`.

Alternatively, it might be nice if I could better leverage the options system to set up my `CorsOptions` instance.

The current setup seems to force me to either move lots of definitions to an extension method, or I end up having to leave them inside of my `Startup.cs`, which obviously gets quite big.

**Comment by brockallen** [comment]
You mean some way to load policies dynamically (e.g. from a DB)?

**Comment by atrauzzi** [comment]
Well, not from a DB.  But I have some `IOptions` instances that have values I'd love to get into my policy.  So maybe not as heavy as DB ;)

**Comment by brockallen** [comment]
For me I need a DB. I was just wondering if we could achieve 2 birds with 1 stone here.

**Comment by atrauzzi** [comment]
It's possible.  I wouldn't be surprised if somehow the approach was similar.

**Comment by Eilon** [comment]
We have no plans to implement this in the box, but we do have an example of a dynamic CORS policy provider here: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.DynamicCorsPolicyProvider (the example uses MVC, but the CORS stuff is all the same regardless of MVC).

You could certainly use that sample as a starting point to implement other types of CORS providers. If you come up with something and publish it, we'd be happy to link to it.
